### ISSUE TITLE
Instance creation for workflow service

### ISSUE THREAD

**Issue by srinivasnrao** [SAP-samples/teched2020-DEV264#2]
Hi Team,

- I am unable to understand why do we need to create a separate instance and key for "Workflow Service" when the booster already creates an instance for it? 
- Also, why doesn't the booster put in at least the basic authorizations ( _may be GET operation_ ) in the service instance created by it ?
- If it is as per the design to separately create instance, then how is "wm_workflow" instance useful ? Isn't it duplicate to what we create manually?

Thanks & Regards
Srinivas Rao.

**Comment by srinivasnrao** [comment]
@venugopalchembrakalathil @rich-heilman  - Could you please help me to understand ?

**Comment by ArchanaShukla** [comment]
Hello @srinivasnrao,
Here are the answers in order:

1. Workflow Service Instance provides the needed access to the APIs based on the scope assigned. The default "wm_workflow" instance created by the booster have the default scopes (TASK_GET, FORM_DEFINITION_DEPLOY, TASK_DEFINITION_GET, WORKFLOW_DEFINITION_DEPLOY) because these covers all the scenarios. For APIs call, you need to explicitly create new workflow service instance of needed scopes. 
2. As mentioned above, Booster creates default workflow service instance with basic default scopes. 
3. "wm_workflow" service instance is used while importing the content from API Hub using Process Flexibility application, the same instance can be used to deploy workflow MTAs from Business Application Studio. 

Hope that answers!

**Comment by srinivasnrao** [comment]
Thanks @ArchanaShukla. Clears the doubt. Thank you very much !
